### ISSUE TITLE
Check commits GHA job sometimes returns an intermittent 404

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#2450]
```
Error running commitlint RequestError [HttpError]: Not Found
    at /home/runner/work/design-system/design-system/node_modules/@octokit/request/dist-node/index.js:76:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runCommitLint (/home/runner/work/design-system/design-system/scripts/commitlint/index.js:35:25) {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-length': '91',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 10 Jun 2021 11:38:19 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '07C0:5528:52F164:EBDC63:60C1F9AB',
    'x-ratelimit-limit': '60',
    'x-ratelimit-remaining': '58',
    'x-ratelimit-reset': '1623328699',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '2',
    'x-xss-protection': '0'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/Royal-Navy/design-system/pulls//commits',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.5.6 octokit-core.js/3.4.0 Node.js/14.17.0 (linux; x64)'
    },
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest'
```

https://github.com/Royal-Navy/design-system/pull/2449/checks?check_run_id=2793011926

**Comment by hxltrhuxze** [comment]
Discussed: Just run GHA jobs on PR open. Closing in favour of #2080
